=== raksjnu/apiguard/reference/tibco_projects/Tibco2MuleAcceleratorv2/Resources/Schema/Tibco/Conversion.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://ibm.com/raks/tibco2mule/accelerator/Resources/Schema/Conversion.xsd"
	 targetNamespace="http://ibm.com/raks/tibco2mule/accelerator/Resources/Schema/Conversion.xsd"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:element name="ConversionInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="conversion" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tibcoType" type="xs:string" minOccurs="0"/>
							<xs:element name="muleType" type="xs:string" minOccurs="0"/>
							<xs:element name="conversionImpl" type="xs:string" minOccurs="0"/>
							<xs:element name="issueType" type="xs:string" minOccurs="0"/>
							<xs:element name="remarks" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="List">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="list" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ActivityType" minOccurs="0"/>
				<xs:element ref="TibcoName" minOccurs="0"/>
				<xs:element ref="Tibco" minOccurs="0"/>
				<xs:element ref="Mule" minOccurs="0"/>
				<xs:element ref="Implementation" minOccurs="0"/>
				<xs:element name="Type" type="xs:string" minOccurs="0"/>
				<xs:element ref="Remarks" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ActivityType" type="xs:string"/>
	<xs:element name="TibcoName" type="xs:string"/>
	<xs:element name="Tibco" type="xs:string"/>
	<xs:element name="Mule" type="xs:string"/>
	<xs:element name="Implementation" type="xs:string"/>
	<xs:element name="Remarks" type="xs:string"/>
</xs:schema>

=== raksjnu/apiguard/reference/tibco_projects/Tibco2MuleAcceleratorv2/Resources/SharedVariables/ConversionSharedVariable.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<ns0:ConversionInfo xmlns:ns0 = "http://www.tibco.com/schemas/Tibco2MuleAccelerator/Resources/Schema/Tibco/Conversion.xsd" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://www.tibco.com/schemas/Tibco2MuleAccelerator/Resources/Schema/Tibco/Conversion.xsd ../Schema/Tibco/Conversion.xsd">
	<ns0:conversion>
		<ns0:tibcoType>Start</ns0:tibcoType>
		<ns0:muleType>N/A</ns0:muleType>
		<ns0:conversionImpl>N/A</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>MapperActivity</ns0:tibcoType>
		<ns0:muleType>transform-message</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>FileReadActivity</ns0:tibcoType>
		<ns0:muleType>File</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>FileWriteActivity</ns0:tibcoType>
		<ns0:muleType>File</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>FileCreateActivity</ns0:tibcoType>
		<ns0:muleType>File</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>FileRemoveActivity</ns0:tibcoType>
		<ns0:muleType>File</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>AssignActivity</ns0:tibcoType>
		<ns0:muleType>variable-transformer</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>WriteToLogActivity</ns0:tibcoType>
		<ns0:muleType>logger</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>GenerateErrorActivity</ns0:tibcoType>
		<ns0:muleType>N/A</ns0:muleType>
		<ns0:conversionImpl>N</ns0:conversionImpl>
	</ns0:conversion>
	<ns0:conversion>
		<ns0:tibcoType>JavaActivity</ns0:tibcoType>
		<ns0:muleType>custom-transformer~component</ns0:muleType>
		<ns0:conversionImpl>Y</ns0:conversionImpl>
	</ns0:conversion>
</ns0:ConversionInfo>
